services:
  - type: web
    name: hotel-management
    env: php
    plan: free
    buildCommand: |
      # Install PHP dependencies if any
      echo "Building PHP application..."
      # No build step needed for pure PHP
    startCommand: |
      # Start PHP built-in server
      php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: hotel-db
    plan: free
    databaseName: hotel_management
    user: hotel_user
