services:
  - type: web
    name: hotel-management
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: hotel-db
    plan: free
    databaseName: hotel_management
    user: hotel_user
